steps:
  # 1. Docker imajını build et
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/bootcamp-system-497710/docker-repo/php-app:latest', '-f', 'docker/Dockerfile', '.']
  
  # 2. İmajı push et
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/bootcamp-system-497710/docker-repo/php-app:latest']

  # 3. Kubernetes'i güncelle
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=bootcamp-cluster' # Kendi cluster ismini yaz
